INSERT INTO `courses` (`code`, `credits`, `name`)
VALUES ('COMP-1000', 3, 'Key Concepts in Computer Science'),
       ('ENGL-1001', 3, 'Composition'),
       ('ENGL-1005', 3, 'Topics in Literature'),
       ('MATH-1020', 3, 'Mathematical Foundations'),
       ('COMP-1047', 3, 'Computer Concepts for End-Users'),
       ('ECON-1100', 3, 'Introduction to Economics I'),
       ('ECON-1110', 3, 'Introduction to Economics II'),
       ('PSYC-1150', 3, 'Introduction to Psychology as a Behavioural Science'),
       ('MATH-1250', 3, 'Linear Algebra I'),
       ('MATH-1260', 3, 'Vectors and Linear Algebra'),
       ('PHIL-1290', 3, 'Contemporary Moral Issues'),
       ('MKTG-1310', 3, 'Principles of Marketing'),
       ('COMP-1400', 3, 'Introductions to Algoritms and Programming I'),
       ('COMP-1410', 3, 'Introduction to Algorithms and Programming II'),
       ('ACCT-1510', 3, 'Principles of Financial Accounting'),
       ('MATH-1720', 3, 'Differential Calculus'),
       ('MATH-1730', 3, 'Integral Calculus'),
       ('MATH-1760', 3, 'Functions and Differential Calculus'),
       ('MSCI-2020', 3, 'Business Data Analysis'),
       ('COMP-2057', 3, 'Introduction to the Internet'),
       ('COMP-2067', 3, 'Programming for Beginners'),
       ('COMP-2077', 3, 'Problem Solving and Information on the Internet'),
       ('GART-2090', 3, 'Ethics in the Professions'),
       ('COMP-2097', 3, 'Social Media Marketing for End Users'),
       ('CMAF-2100', 3, 'Speech Communication to Inform'),
       ('COMP-2120', 3, 'Object-Oriented Programming Using Java'),
       ('MSCI-2130', 3, 'Introduction to Management Information Systems'),
       ('COMP-2140', 3, 'Computer Languages, Grammers, and Translators'),
       ('PSYC-2180', 3, 'Everyday Conflicts and Their Resolution'),
       ('MSCI-2200', 3, 'Quantitative Decision Models I'),
       ('CMAF-2210', 3, 'The Art of Photo-blogging'),
       ('PHIL-2240', 3, 'Business Ethics'),
       ('PHIL-2280', 3, 'Technology, Human Values and the Environment'),
       ('COMP-2310', 3, 'Theoretical Foundations of Computer Science'),
       ('MGMT-2400', 3, 'Management and Organizational Life'),
       ('COMP-2540', 3, 'Data Structures and Algorithms'),
       ('ACCT-2550', 3, 'Principles of Managerial Accounting'),
       ('COMP-2560', 3, 'Systems Programming'),
       ('COMP-2650', 3, 'Computer Architecture I: Digital Design'),
       ('COMP-2660', 3, 'Computer Architecture II: Microprocessor Programming'),
       ('FINA-2700', 3, 'Business Finance I'),
       ('COMP-2707', 3, 'Advanced Web Design, Construction, and Deployment'),
       ('COMP-2750', 3, 'Selected Topics'),
       ('COMP-2800', 3, 'Software Development'),
       ('STAT-2910', 3, 'Statistics for the Sciences'),
       ('STAT-2920', 3, 'Introduction to Probability'),
       ('COMP-2980', 3, 'Co-op Work Term I'),
       ('COMP-3057', 3, 'Cyber-Ethics'),
       ('COMP-3077', 3, 'Web-Based Data Management'),
       ('COMP-3110', 3, 'Introduction to Software Engineering'),
       ('COMP-3150', 3, 'Database Management Systems'),
       ('MSCI-3200', 3, 'Quantitative Decision Models II'),
       ('COMP-3220', 3, 'Object-Oriented Software Analysis and Design'),
       ('COMP-3300', 3, 'Operating Systems Fundamentals'),
       ('COMP-3340', 3, 'World Wide Web Information Systems Development'),
       ('COMP-3400', 3, 'Advanced Object Oriented System Design Using C++'),
       ('COMP-3500', 3, 'Introduction to Multimedia Systems'),
       ('COMP-3520', 3, 'Introduction to Computer Graphics'),
       ('COMP-3540', 3, 'Theory of Computation'),
       ('COMP-3670', 3, 'Computer Networks'),
       ('COMP-3680', 3, 'Network Practicum'),
       ('COMP-3710', 3, 'Artificial Intelligence Concepts'),
       ('COMP-3750', 3, 'Selected Topics'),
       ('COMP-3760', 3, 'Selected Topics'),
       ('COMP-3770', 3, 'Game Design, Development and Tools'),
       ('MATH-3800', 3, 'Numerical Methods'),
       ('MATH-3940', 3, 'Numerical Analysis for Computer Scientists'),
       ('COMP-3980', 3, 'Co-op Work Term II'),
       ('COMP-4110', 3, 'Software Verification and Testing'),
       ('COMP-4150', 3, 'Advanced and Practical Database Systems'),
       ('COMP-4200', 3, 'Mobile Application Development'),
       ('COMP-4220', 3, 'Agile Software Development'),
       ('COMP-4250', 3, 'Big Data Analytics and Database Design'),
       ('COMP-4400', 3, 'Principles of Programming Languages'),
       ('COMP-4500', 3, 'Multimedia System Development'),
       ('COMP-4540', 3, 'Design and Analysis of Computer Algorithms'),
       ('COMP-4670', 3, 'Network Security'),
       ('COMP-4680', 3, 'Advanced Networking'),
       ('COMP-4700', 3, 'Project Using Selected Tools'),
       ('COMP-4730', 3, 'Advanced Topics in Artificial Intelligence I'),
       ('COMP-4740', 3, 'Advanced Topics in Artificial Intelligence II'),
       ('COMP-4750', 3, 'Selected Topics'),
       ('COMP-4760', 3, 'Selected Topics'),
       ('COMP-4770', 3, 'Artificial Intelligence for Games'),
       ('COMP-4800', 3, 'Selected Topics in Software Engineering'),
       ('COMP-4960', 6, 'Research Project'),
       ('COMP-4970', 3, 'Co-op Work Term III'),
       ('COMP-4980', 3, 'Co-op Work Term IV'),
       ('COMP-4990', 3, 'Project Management: Techniques and Tools'),
       ('STEN-1000', 3, 'Introduction to Business'),
       ('DRAM-2100', 3, 'Speech Communication to Inform'),
       ('PHIL-2210', 3, 'Introduction to Ethics');